### ISSUE TITLE
Google calendar frontend & backend implementation

### ISSUE THREAD

**Issue by Jozefwl** [Miki-Herman/Financio#10]
- Backend: There needs to be a token saved for the google API, but also one for the app
- Backend: Google token must be saved somewhere, but backend token can be made (signed) on backend to auth the user
- Backend: How to incorporate google token to be same as app token / work ?
- [Create Calendar Events in React With Google Calendar API and Supabase (Supabase Providers Tutorial)](https://www.youtube.com/watch?v=tgcCl52EN84)
- Frontend: Internal calendar showing unpaid payments or just a list?
- Synchronization: how to check for already existing events?
- Synchronization: add identifier for Financio events?

There needs to be a new component made, which will contain the google logic, but google login also needs to be fixed because it doesn't contain calendar scopes. (OAuth integration into backend?)

**Comment by MrBlackGhostt** [comment]
@Jozefwl i want to contribute to this issue can you assign it to me

**Comment by Jozefwl** [comment]
Resolved in [this commit](https://github.com/Miki-Herman/Financio/commit/e2ff20be3f7be3d76c5e5514fe9394eb2bd8c284)
